version: '3.8'

services:
  
  # Database - Mongo DB
  mongo:
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: helpdev
      # MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Database Manager
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8099:8081
    depends_on:
      - mongo
    environment:
      # ME_CONFIG_BASICAUTH_USERNAME: express
      # ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: helpdev
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
      
volumes:
  db:
    driver: local